admin_slider_slider_create:
    path: /create
    defaults:
        _controller: \Mindy\Bundle\SliderBundle\Controller\Admin\SliderController::create

admin_slider_slider_list:
    path: /list
    defaults:
        _controller: \Mindy\Bundle\SliderBundle\Controller\Admin\SliderController::list

admin_slider_slider_update:
    path: /update/{id}
    defaults:
        _controller: \Mindy\Bundle\SliderBundle\Controller\Admin\SliderController::update
    requirements:
        id: \d+

admin_slider_slider_remove:
    path: /remove/{id}
    defaults:
        _controller: \Mindy\Bundle\SliderBundle\Controller\Admin\SliderController::remove
    requirements:
        id: \d+
